### ISSUE TITLE
[question] is it possible to use this on postgis geometry

### ISSUE THREAD

**Issue by DeoLeung** [pramsey/pgsql-arraymath#3]
just for curiosity

is it possible to use this on `geometry`?

 it sounds possible to use this approach to do some `bd09`, `gcj02` transform

**Comment by pramsey** [comment]
I don't understand the question.

**Comment by DeoLeung** [comment]
in `postgis` usually we can do `st_transform(geometry, 3857)` to transform to different srs

however it does not support China special [bd09, gcj02](https://github.com/googollee/eviltransform/blob/master/c/transform.c)

if I want to do it in the db, I need to apply to math calculation to all the points(sounds like array).

currently I have the transform function like
```sql
CREATE OR REPLACE FUNCTION public.GCJ2WGS(IN gcj_lng double precision,
                                          IN gcj_lat double precision,
                                          OUT lng double precision,
                                          OUT lat double precision)
```
I tried `ST_DumpPoints` to get a list of points and apply the function but not sure how to currently collect it back to the correct geometry efficiently

I have another solution to transform it as `wkt` and regex replace the points with the transformed dump points

so I wonder whether this extension can do something like `to_array(geometry)` then do some array math and then properly convert it back to correct `geometry`

**Comment by pramsey** [comment]
Certainly as written, no, this won't do that. And even with some ability to handle geometry, it isn't conceptually what you want, as you really want an iterator over geometry coordinates, not over arrays of geometry. An iterator would be an interesting idea, but perhaps tragically slow, though maybe that wouldn't matter. 

Is there a reason you aren't working on upstream to get your coordinate systems supported in Proj directly?

**Comment by pramsey** [comment]
In answer to my question: https://github.com/OSGeo/PROJ/issues/982
A patch on proj would still seem to be the best approach, since that would maximize the amount of software that could take advantage...

**Comment by DeoLeung** [comment]
I c, thanks for the classification.

one thing is we have limited `c++` skill, but sure I think the better solution shall be the link above :)

**Comment by Artoria2e5** [comment]
I can write a proj patch if you want it, but just keep in mind that these things will be pretend "projections" because, well, the datum transformations assume that the same 3d space is being referred to, which is not the case for these curvy lines from trig.

**Comment by Artoria2e5** [comment]
And FYI, @gumblex has a PGSQL version of the two geo obfuscations algorithms in https://github.com/Artoria2e5/PRCoords/tree/master/pgsql.

The non-iterative algorithms contain no data-dependent branches and are probably array-able, but I don't really see much direct benefit.
