### ISSUE TITLE
Index support

### ISSUE THREAD

**Issue by elb3k** [pramsey/pgsql-arraymath#8]
A bit of long shot question!

I have a table with face embeddings (2622-dimensional float8 array).
And using array operations to calculate `cosine_distance` between embeddings.  It works fine, but does not scale well with many rows, because there are no index that support big array types.

Is there any tip, or support for **GIST/GIN** indexing for float8 array type ?

**Comment by pramsey** [comment]
Not in this extension... interesting problem. A binning strategy with a GIN index might work. The little reading I've done on high dimensionality indexes seems to indicate they are "hard" :) ... maybe in concert with a dimensional reduction strategy to make the data amenable to a convention index like an rtree.
