### ISSUE TITLE
Make arraymath more robust against empty arrays

### ISSUE THREAD

**Issue by jschultz** [pramsey/pgsql-arraymath#9]
Currently adding two empty arrays produces the following:

> \# select array[]::integer[] @+ array[]::integer[];
> NOTICE:  Hello from ArrayMath 1.0
> ERROR:  only 1-dimensional arrays supported
> CONTEXT:  SQL function "array_plus_array" statement 1

The error message isn't very helpful as both empty arrays are cast as 1-dimensional. And the sum of two empty arrays should be an empty array.

**Comment by pramsey** [comment]
What about the sum of a non-empty array and an empty array?
